import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Styles from "./globals.module.css";
import { createStore } from "@reduxjs/toolkit";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "m_kadirov | Minimalistic portfolio",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={Styles.html}>
    
      <body className={Styles.body}>{children}</body>
    </html>
  );
}
